### ISSUE TITLE
Improve output in case of no failing checks

### ISSUE THREAD

**Issue by sbourlon** [colis-anr/lintshell#8]
Hi Yann and Nicolas, I wanted to give it a try but the installer didn't find the package. Thanks for your support.

**Comment by Niols** [comment]
Hi Stefan,

I must admit that the README is quite optimistic here, assuming an OPAM package exists when there isn't even a release yet. If you want to try it *via* OPAM, you can pin it:

    opam pin lintshell.dev https://github.com/colis-anr/lintshell.git

If you don't like pinning, you can also:

- clone this repository and `cd` to it,
- install the dependencies: `opam install . --deps-only`,
- build lintshell: `make`,
- play with it: `bin/lintshell check test.sh`,
- or install it manually: `make install`.

I'll update the README to be more realistic.

**Comment by sbourlon** [comment]
Thank you Nicolas, I had to run `eval $(opam env)` after `opam install . --deps-only` to find `dune`.

`bin/lintshell check test.sh` on my script returned nothing, is it expected? Maybe printing on stderr a list of passing and failing checks would help?

**Comment by Niols** [comment]
Thanks for the remark!

Yes, I think that's what lintshell does when there is no failing check. There should definitely be a message then. And probably have a more verbose mode with a list of passing and failing checks, indeed.
